In [1]:
import numpy as np

b：给每个元素内部扩展了一维
c：在外部扩展了一维
维度从0到N分别是最外层的中括号和最内层的中括号

In [7]:
a = np.arange(0,40,10)
print('a:',a)
b = np.arange(0,40,10)[:,np.newaxis]
print('b:',b)
c = np.arange(0,40,10)[np.newaxis,:]
print('c:',c)

a: [ 0 10 20 30]
b: [[ 0]
 [10]
 [20]
 [30]]
c: [[ 0 10 20 30]]


## tile操作：想扩充维度，必须用tuple(3,1)，如果只用一个3,就是同维度下复制了三份，当然，如果你真用乘法a*3，因为是针对ndarray，这里是对里边的数字做广播乘法

In [20]:
a = np.arange(0,40,10)
print(a.shape)
print(a)
b = np.tile(a,(3,1))
print(b.shape)
print(b)
c = np.tile(a,3)
print(c.shape)
print(c)
d = a * 3
print(d.shape)
print(d)
#print(a.T)
#help(np.tile)

(4,)
[ 0 10 20 30]
(3, 4)
[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
(12,)
[ 0 10 20 30  0 10 20 30  0 10 20 30]
(4,)
[ 0 30 60 90]


广播加法

In [26]:
a = np.arange(0,40,10)[:,np.newaxis]
b = np.array([0, 1, 2])
print(a)
print(a.shape)
print(b)
print(b.shape)
c = a + b
print(c)
print(c.shape)


[[ 0]
 [10]
 [20]
 [30]]
(4, 1)
[0 1 2]
(3,)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
(4, 3)
