In [2]:
import numpy as np



In [28]:
ar = np.arange(0,12).reshape(3,4)
print(ar)
o = np.ones((2,3),dtype=np.float16)
print(o)
e = np.empty((3,2))
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  0.00000000e+000   4.94065646e-324]
 [  9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323]]


In [17]:



#print(np.zeros((3,4)))
#print np.ones((3,4))
#print("np.twos((3,4)):",np.twos((3,4)))#error no api
print("np.eye(3):\n",np.eye(3))

np.eye(3):
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
print("np.zeros((3,4,5)):\n",np.zeros((2,3,4)))

np.zeros((3,4,5)):
 [[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [18]:
a = np.zeros((2,2,2),dtype = np.int32)
print("a:\n",a)
print("a.ndim:",a.ndim)
print("a.shape:",a.shape)
print("a.size:",a.size)
print("a.dtype:",a.dtype)
print("a.itemsize:",a.itemsize)

a:
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
a.ndim: 3
a.shape: (2, 2, 2)
a.size: 8
a.dtype: int32
a.itemsize: 4


## zeros_like()
应该是用了参数x的shape，然后生成了全0的ndarray

In [25]:
x = np.arange(6).reshape(2,3)
x2 = np.arange(3, dtype = float)
print('x is ',x)
print('x2 is ',x2)
print(np.zeros_like(x))
print(np.zeros_like(x2))
print(np.zeros_like((2,3)))#但是你不能直接传参一个shape，结果不符合预期。
print(np.zeros_like([3,3]))

x is  [[0 1 2]
 [3 4 5]]
x2 is  [ 0.  1.  2.]
[[0 0 0]
 [0 0 0]]
[ 0.  0.  0.]
[0 0]
[0 0]


## 原长度同样是9,5点4段和6点5段取前4段的区别
### 间隔从9/4=2.25变成9/5=1.8，最终的覆盖区间也缩水了一个1.8

In [32]:
lin = np.linspace(1,10,5)
print(lin)
lin = np.linspace(1,10,5,endpoint=False)
print(lin)
print(type(lin))

[  1.     3.25   5.5    7.75  10.  ]
[ 1.   2.8  4.6  6.4  8.2]
<class 'numpy.ndarray'>


# diff是算相邻元素的差值的
但是可以看到，3*4的数组只有3*3的差值，因为这是要指定轴向的,不是flatten的。
#Calculate the n-th discrete difference along given axis.

In [46]:
A = np.arange(12).reshape(3,4)
#A = np.arange(0,24,2).reshape(3,4)
print("A:",A)
print('diff:\n',np.diff(A))
print('diff:\n',np.diff(A,axis=0))
#错误写法，不支持
#print('diff:\n',np.diff(A,axis=0,1)
#print('diff:\n',np.diff(A,axis=(0,1))


A: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
diff:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
diff:
 [[4 4 4 4]
 [4 4 4 4]]


In [47]:
print(A.T)
print(np.transpose(A))
print(np.clip(A,5,9))
print(np.nonzero(A))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[5 5 5 5]
 [5 5 6 7]
 [8 9 9 9]]
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


# exp e的n次方。实现softmax

In [71]:
scores = np.array([123,456,789])
scores = np.array([25,51,49])
scores = np.array([1,1,1])#这个比较好观察，均衡的，概率都是0.3333
scores2 = scores.copy()
print(scores)
scores -= np.max(scores)

print('scores:',scores)
print('scores2:',scores2)

[1 1 1]
scores: [0 0 0]
scores2: [1 1 1]


In [72]:
#softmax
p = np.exp(scores)/np.sum(np.exp(scores))
#p2 = np.exp(scores2)/np.sum(np.exp(scores2))
print('p:',p)
#print('p2:',p2)

p: [ 0.33333333  0.33333333  0.33333333]


In [67]:
print(np.exp(-1000))
print(np.exp(-100))
print(np.exp(-10))
print(np.exp(-1))
print(np.exp(0))
print(np.exp(1))
print(np.exp(10))
print(np.exp(100))

0.0
3.72007597602e-44
4.53999297625e-05
0.367879441171
1.0
2.71828182846
22026.4657948
2.68811714182e+43
