In [2]:
import numpy as np



In [28]:
ar = np.arange(0,12).reshape(3,4)
print(ar)
o = np.ones((2,3),dtype=np.float16)
print(o)
e = np.empty((3,2))
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  0.00000000e+000   4.94065646e-324]
 [  9.88131292e-324   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323]]


In [17]:



#print(np.zeros((3,4)))
#print np.ones((3,4))
#print("np.twos((3,4)):",np.twos((3,4)))#error no api
print("np.eye(3):\n",np.eye(3))

np.eye(3):
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [7]:
print("np.zeros((3,4,5)):\n",np.zeros((2,3,4)))

np.zeros((3,4,5)):
 [[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [18]:
a = np.zeros((2,2,2),dtype = np.int32)
print("a:\n",a)
print("a.ndim:",a.ndim)
print("a.shape:",a.shape)
print("a.size:",a.size)
print("a.dtype:",a.dtype)
print("a.itemsize:",a.itemsize)

a:
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
a.ndim: 3
a.shape: (2, 2, 2)
a.size: 8
a.dtype: int32
a.itemsize: 4


## zeros_like()
应该是用了参数x的shape，然后生成了全0的ndarray

In [25]:
x = np.arange(6).reshape(2,3)
x2 = np.arange(3, dtype = float)
print('x is ',x)
print('x2 is ',x2)
print(np.zeros_like(x))
print(np.zeros_like(x2))
print(np.zeros_like((2,3)))#但是你不能直接传参一个shape，结果不符合预期。
print(np.zeros_like([3,3]))

x is  [[0 1 2]
 [3 4 5]]
x2 is  [ 0.  1.  2.]
[[0 0 0]
 [0 0 0]]
[ 0.  0.  0.]
[0 0]
[0 0]


## 原长度同样是9,5点4段和6点5段取前4段的区别
### 间隔从9/4=2.25变成9/5=1.8，最终的覆盖区间也缩水了一个1.8

In [32]:
lin = np.linspace(1,10,5)
print(lin)
lin = np.linspace(1,10,5,endpoint=False)
print(lin)
print(type(lin))

[  1.     3.25   5.5    7.75  10.  ]
[ 1.   2.8  4.6  6.4  8.2]
<class 'numpy.ndarray'>


# diff是算相邻元素的差值的
但是可以看到，3*4的数组只有3*3的差值，因为这是要指定轴向的,不是flatten的。
#Calculate the n-th discrete difference along given axis.

In [46]:
A = np.arange(12).reshape(3,4)
#A = np.arange(0,24,2).reshape(3,4)
print("A:",A)
print('diff:\n',np.diff(A))
print('diff:\n',np.diff(A,axis=0))
#错误写法，不支持
#print('diff:\n',np.diff(A,axis=0,1)
#print('diff:\n',np.diff(A,axis=(0,1))


A: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
diff:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
diff:
 [[4 4 4 4]
 [4 4 4 4]]


In [47]:
print(A.T)
print(np.transpose(A))
print(np.clip(A,5,9))
print(np.nonzero(A))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[5 5 5 5]
 [5 5 6 7]
 [8 9 9 9]]
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


# 加减乘除，三角函数

In [52]:
import math

In [56]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
print(b**2)
print(10*np.sin(a))
print(10*np.cos(a))
a = [math.pi]
print(a)
print(10*np.sin(a))

[10 20 30 40] [0 1 2 3]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[-8.39071529  4.08082062  1.5425145  -6.66938062]
[3.141592653589793]
[  1.22464680e-15]


In [60]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))
print('a:',a)
print('b:',b)
print('a*b:',a*b)
print('dot:',np.dot(a,b))#2*2的，dot也还是2*2的
print(a.dot(b))#不同写法
print(b.dot(a))#左右颠倒

a: [[1 1]
 [0 1]]
b: [[0 1]
 [2 3]]
a*b: [[0 1]
 [0 3]]
dot: [[2 4]
 [2 3]]
[[2 4]
 [2 3]]
[[0 1]
 [2 5]]


In [61]:
a = np.random.random((2,4))
#a = np.random.random((2,4),seed = 12)
print(a)
print('sum:',np.sum(a))
print('axis=1:',np.sum(a,axis=1))
print('min:',np.min(a))
print('axis=0:',np.min(a,axis=0))
print('max:',np.max(a))
print('axis=1',np.max(a,axis=1))
print(np.mean(a))

[[ 0.36746842  0.39948856  0.32944245  0.54274446]
 [ 0.73491647  0.40828899  0.74229828  0.77712287]]
sum: 4.30177050507
axis=1: [ 1.63914389  2.66262661]
min: 0.329442451777
axis=0: [ 0.36746842  0.39948856  0.32944245  0.54274446]
max: 0.777122867036
axis=1 [ 0.54274446  0.77712287]
0.537721313134


# exp e的n次方。实现softmax

In [ ]:
scores = np.array([123,456,789])
scores = np.array([25,51,49])
scores = np.array([1,1,1])#这个比较好观察，均衡的，概率都是0.3333
scores2 = scores.copy()
print(scores)
scores -= np.max(scores)

print('scores:',scores)
print('scores2:',scores2)

In [ ]:
#softmax
p = np.exp(scores)/np.sum(np.exp(scores))
#p2 = np.exp(scores2)/np.sum(np.exp(scores2))
print('p:',p)
#print('p2:',p2)

In [ ]:
print(np.exp(-1000))
print(np.exp(-100))
print(np.exp(-10))
print(np.exp(-1))
print(np.exp(0))
print(np.exp(1))
print(np.exp(10))
print(np.exp(100))

# argmin argmax argsort average cumsum median

In [81]:
A = np.arange(2,14).reshape((3,4))
A = np.array([[10,5],[30,5]])
print(A)
print(np.argmin(A))#返回最小元素的下标
print(A.argmin())
print(A.argmax())


[[10  5]
 [30  5]]
1
1
2


In [82]:
print(np.average(A))
print(np.sum(A))

12.5
50


In [85]:
#中位数，如果奇数个元素，取中间那个，偶数个，取中间两个的平均值。
A = np.array([[10,5],[30,5]])
print(np.median(A))
A = np.array([[1,5,8]])
print(np.median(A))

7.5
5.0


In [86]:
#累加，1,1+5,1+5+8
print(np.cumsum(A))

[ 1  6 14]


In [95]:
print('flatten:',A.flatten())
print('a.flat:',A.flat)
print('type of flat:',type(A.flat))#numpy.flatiter
for item in A.flat:#能访问到iter的要遍历的数值，而不只是这个iter对象。
	print('flat iteration:',item)

flatten: [ 2  3  4  5  6  7  8  9 10 11 12 13]
a.flat: <numpy.flatiter object at 0x14055d0>
type of flat: <class 'numpy.flatiter'>
flat iteration: 2
flat iteration: 3
flat iteration: 4
flat iteration: 5
flat iteration: 6
flat iteration: 7
flat iteration: 8
flat iteration: 9
flat iteration: 10
flat iteration: 11
flat iteration: 12
flat iteration: 13


In [107]:
#排序对应的下标
x = np.array([3, 0, 7, -1, 9, 5])
i = x.argsort()
print('stepping:',x[::1])
print('reverse stepping:',x[::-1])
print('i:',i)
print('i reversed:',i[::-1])#没有reverse选项，可以直接反过来。# i = x.argsort(reverse=True)
print('-i:',-i)#这个不行

for index_ in i:
    print(x[index_],end = ' ')
print()
print('x[i]):',x[i])
print('x[-i]):',x[-i])#cannot range reversely!!!!!!!!!!!!!!!!!负数的含义就变了，-1是倒数第一个。



stepping: [ 3  0  7 -1  9  5]
reverse stepping: [ 5  9 -1  7  0  3]
i: [3 1 0 5 2 4]
i reversed: [4 2 5 0 1 3]
-i: [-3 -1  0 -5 -2 -4]
-1 0 3 5 7 9 
x[i]): [-1  0  3  5  7  9]
x[-i]): [-1  5  3  0  9  7]


In [114]:
#排序，取top-k，的，下标。不过是升序，想更像top-k的话换个顺序。
print('index:', x.argsort()[-5:])
print('index:', x.argsort()[-5:][::-1])#下标4对应9,最大，下标2对应7,第二大，降序的top-k。


index: [1 0 5 2 4]
index: [4 2 5 0 1]
[-1  0  3  5  7  9]


In [122]:
#index再读回具体的数值
print(x[x.argsort()[-7:]])#upsent order of x

[-1  0  3  5  7  9]


In [130]:
index_list = x.argsort()[-7:]#upsent order of x
for i_ in index_list:
    print('x:', x[i_],end = ' ')
print()
index_list = x.argsort()[-7:][::-1]  # descent order of x
for i_ in index_list:
    print('x:', x[i_], end = ' ')

x: -1 x: 0 x: 3 x: 5 x: 7 x: 9 
x: 9 x: 7 x: 5 x: 3 x: 0 x: -1 

In [127]:
#我胡乱写的，虽然能运行，但是没意义
x = np.array([3, 0, 7, -1, 9, 5])
print(x)
print('wrong demo:', x.argsort()[x.argsort()[-6:]])
#拆解
print(x.argsort()[-5:])#升序，后5个，6个不好对比，这样就排除-1,取了top-5
#print([x.argsort()[-5:]])#外套list，其实没意义，组合才有意义
print(x.argsort()[x.argsort()[-6:]])#组合起来是取top-5下标，用下标再去处理下标，所以没意义。
#print(x.argsort()x.argsort()[-6:])#所以方括号还是要的

[ 3  0  7 -1  9  5]
wrong demo: [5 1 3 4 0 2]
[1 0 5 2 4]
[5 1 3 4 0 2]


In [98]:
help(np.argsort)

Help on function argsort in module numpy.core.fromnumeric:

argsort(a, axis=-1, kind='quicksort', order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort'}, optional
        Sorting algorithm.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still 

# 行列迭代访问

In [92]:
A = np.arange(2,14).reshape((3,4))
print(A)
for row in A:
    print('row iteration:',row)
for column in A:#其实和row一样，这只是二维数组的最外围，只是个name，for循环的特性，早期我不知道。
	print('fake column iteration:',column)
for real_column in A.T:#这才是直觉上的那个列
    print('column iteration:',real_column)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
row iteration: [2 3 4 5]
row iteration: [6 7 8 9]
row iteration: [10 11 12 13]
fake column iteration: [2 3 4 5]
fake column iteration: [6 7 8 9]
fake column iteration: [10 11 12 13]
column iteration: [ 2  6 10]
column iteration: [ 3  7 11]
column iteration: [ 4  8 12]
column iteration: [ 5  9 13]
