# npy数据文件，也能存数据结构，还不想pickle那么麻烦需要转换

In [1]:
import numpy as np

In [2]:
np.save('temp/123',np.array([[1,2,3],[4,5,6]]))#default postfix .npy

In [7]:
#a = np.load('temp/123')#error,default postfix is .npy,then the file is 123.npy
a = np.load('temp/123.npy')
print(a)

[[1 2 3]
 [4 5 6]]


## 字典形式npz？

In [8]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2])
np.savez('temp2/123',a=a,b=b)#字典形式？

这个close和del还是有些区别的。

In [15]:
#data = np.load('temp2/123')#savez's default postfix is npz
data = np.load('temp2/123.npz')
print(data)
print(data['a'])
print(data['b'])
data.close()
print(data)
#print(data['a'])#AttributeError: 'NoneType' object has no attribute 'open'

[[1 2 3]
 [4 5 6]]
[1 2]


In [ ]:
x = np.load('temp/123.npy',mmap_mode='r')
print(x[0,:])

In [20]:
y = np.load('temp2/123.npz',mmap_mode='r')
#print(y[0,:])#TypeError: not all arguments converted during string formatting
print(y)


    mmap_mode : {None, 'r+', 'r', 'w+', 'c'}, optional
        If not None, then memory-map the file, using the given mode (see
        `numpy.memmap` for a detailed description of the modes).  A
        memory-mapped array is kept on disk. However, it can be accessed
        and sliced like any ndarray.  Memory mapping is especially useful
        for accessing small fragments of large files without reading the
        entire file into memory.
如果不是“无”，则使用给定模式对文件进行内存映射（有关模式的详细描述，请参见“numpy.memmap”）。
内存映射数组保存在磁盘上。但是，它可以像任何ndarray一样被访问和切片。内存映射对于在不将整个文件读取到内存的情况下访问大文件的小片段特别有用。